steps:
- name: 'docker/compose:1.19.0'
  args: ['-f', 'docker-compose.yml', 'up', '-d']
  env:
    - 'PROJECT_ID=$PROJECT_ID'
- name: 'docker/compose:1.19.0'
  args: ['-f', 'docker-compose.yml', 'push']
  env:
    - 'PROJECT_ID=$PROJECT_ID'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'image-generation-service'
  entrypoint: 'gcloud'
  args: [
    'run',
    'deploy',
    'image-generation-service',
    '--image', 'gcr.io/$PROJECT_ID/creative-studio/image-generation-service:latest',
    '--region', 'us-central1',
    '--set-env-vars', 'IMAGE_CREATION_BUCKET=$PROJECT_ID-genmedia',
    '--set-env-vars', 'PROJECT_ID=$PROJECT_ID',
    '--set-env-vars', 'REGION=us-central1',
    '--format', 'value(status.url)',
  ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'api-gateway'
  entrypoint: 'gcloud'
  args: [
    'run',
    'deploy',
    'api-gateway',
    '--image', 'gcr.io/$PROJECT_ID/creative-studio/api-gateway:latest',
    '--region', 'us-central1',
    '--set-env-vars', 'PROJECT_NUMBER=$PROJECT_NUMBER',
    '--set-env-vars', 'REGION=us-central1',
    '--format', 'value(status.url)',
  ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'app'
  entrypoint: 'gcloud'
  args: [
    'run',
    'deploy',
    'creative-studio-app',
    '--image', 'gcr.io/$PROJECT_ID/creative-studio/app:latest',
    '--region', 'us-central1',
    '--set-env-vars', 'PROJECT_NUMBER=$PROJECT_NUMBER',
    '--set-env-vars', 'PROJECT_ID=$PROJECT_ID',
    '--set-env-vars', 'IMAGE_CREATION_BUCKET=$PROJECT_ID-genmedia',
    '--set-env-vars', 'REGION=us-central1',
    '--allow-unauthenticated',
    '--format', 'value(status.url)',
  ]