steps:
- name: docker/compose:1.29.2
  args: ['-f', 'docker-compose.yml', 'build']
  env:
    - 'PROJECT_ID=$PROJECT_ID'
- name: 'docker/compose:1.29.2'
  args: ['-f', 'docker-compose.yml', 'push']
  env:
    - 'PROJECT_ID=$PROJECT_ID'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'create tfvars'
  dir: 'terraform'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      iap_brand_id=$(gcloud iap oauth-brands list --format="value(name)" | sed "s:.*/::")
      cat <<EOF > terraform.tfvars
      project_id = "$PROJECT_ID"
      project_number = "$PROJECT_NUMBER"
      region = "us-central1"
      media_bucket = "$PROJECT_ID-genmedia"
      db_name = "genmedia-studio"
      iap_brand_id = "$iap_brand_id"
      EOF
- id: 'tf init'
  name: 'hashicorp/terraform:1.10.0'
  entrypoint: 'sh'
  dir: terraform
  args:
  - '-c'
  - |
      terraform init \
      -backend-config="bucket=$_TF_STATE_BUCKET" \
      -backend-config="prefix=genmedia-studio" \
      -get=true \
      -upgrade \
      -reconfigure
- id: 'tf plan'
  name: 'hashicorp/terraform:1.10.0'
  entrypoint: 'sh'
  dir: terraform
  args:
  - '-c'
  - |
      terraform plan -var-file="./terraform.tfvars" -out="./tfplan"
- id: 'tf apply'
  name: 'hashicorp/terraform:1.10.0'
  entrypoint: 'sh'
  dir: terraform
  args:
  - '-c'
  - |
      terraform apply "./tfplan"