
# Copyright 2025 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3.3"
services:
  generation_service:
    image: 'us-central1-docker.pkg.dev/$PROJECT_ID/genmedia-studio/generation-service:latest'
    build:
      context: .
      dockerfile: ./generation_service/Dockerfile
    ports:
      - "8000:8000"
  file_service:
    image: 'us-central1-docker.pkg.dev/$PROJECT_ID/genmedia-studio/file-service:latest'
    build:
      context: .
      dockerfile: ./file_service/Dockerfile
    ports:
      - "8001:8000"
  api_gateway:
    image: 'us-central1-docker.pkg.dev/$PROJECT_ID/genmedia-studio/api-gateway:latest'
    build:
      context: .
      dockerfile: ./api_gateway/Dockerfile 
    ports:
      - "8002:8000"
  app:
    image: 'us-central1-docker.pkg.dev/$PROJECT_ID/genmedia-studio/app:latest'
    build:
      context: ./app/
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"